version: '3.1'
services:
  myomouselanding:
    container_name: myomouselanding
    build:
      context: ./
      dockerfile: Dockerfile
    #    healthcheck:
    #      test: [ "CMD", "curl", "-sS", "http://127.0.0.1:8000" ]
    #      interval: 5s
    #      timeout: 10s
    #      retries: 3
    ports:
      - "8000:8000"
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped
    volumes:
      - ./:/opt/myomouselanding

